// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String revmTraceTransaction({
  required BigInt chainId,
  required String from,
  required BigInt fromNonce,
  required String to,
  required String data,
  required BigInt gasLimit,
  required BigInt gasPrice,
  required BigInt gasPriorityFee,
  required String latestBlockEnv,
  required String prestateTracerResult,
  required bool isOpStack,
}) => RustLib.instance.api.crateApiTraceRevmTraceTransaction(
  chainId: chainId,
  from: from,
  fromNonce: fromNonce,
  to: to,
  data: data,
  gasLimit: gasLimit,
  gasPrice: gasPrice,
  gasPriorityFee: gasPriorityFee,
  latestBlockEnv: latestBlockEnv,
  prestateTracerResult: prestateTracerResult,
  isOpStack: isOpStack,
);
